Make the Hobbit serverlist (BBDISP, BBDISPLAYS) configurable via the standard /etc/default/hobbitclient setup.
git-svn-id: svn://svn.code.sf.net/p/xymon/code@3739 44351d6e-118b-4698-b696-ce33095ecaa4

diff --git a/trunk/rpm/hobbit-client.init b/trunk/rpm/hobbit-client.init
--- a/trunk/rpm/hobbit-client.init
+++ b/trunk/rpm/hobbit-client.init
@@ -16,21 +16,41 @@ DESC=hobbitclient
 
 test -x $DAEMON || exit 0
 
+CMD="$1"
+
 # Include hobbitclient defaults if available
 DMNOPTS=""
 if [ -f /etc/default/hobbitclient ] ; then
 	. /etc/default/hobbitclient
-	if [ "$CLIENTHOSTNAME" != "" ]; then
-		DMNOPTS="${DMNOPTS} --hostname=${CLIENTHOSTNAME}"
-	fi
-	if [ "$CLIENTOS" != "" ]; then
-		DMNOPTS="${DMNOPTS} --os=${CLIENTOS}"
-	fi
+else
+	echo "Installation failure - missing /etc/default/hobbitclient"
+	exit 1
+fi
+
+if [ "$HOBBITSERVERS" = "" ]; then
+	echo "Please configure HOBBITSERVERS in /etc/default/hobbitclient"
+	exit 1
+fi
+
+set $HOBBITSERVERS
+if [ $# -eq 1 ]; then
+	echo "BBDISP=\"$HOBBITSERVERS\"" >/var/run/hobbitclient-runtime.cfg
+	echo "BBDISPLAYS=\"\"" >>/var/run/hobbitclient-runtime.cfg
+else
+	echo "BBDISP=\"0.0.0.0\"" >/var/run/hobbitclient-runtime.cfg
+	echo "BBDISPLAYS=\"$HOBBITSERVERS\"" >>/var/run/hobbitclient-runtime.cfg
+fi
+
+if [ "$CLIENTHOSTNAME" != "" ]; then
+	DMNOPTS="${DMNOPTS} --hostname=${CLIENTHOSTNAME}"
+fi
+if [ "$CLIENTOS" != "" ]; then
+	DMNOPTS="${DMNOPTS} --os=${CLIENTOS}"
 fi
 
 set -e
 
-case "$1" in
+case "$CMD" in
   start)
 	echo -n "Starting $DESC: "
 	su -c "$DAEMON $DMNOPTS start" - hobbit
